### ISSUE TITLE
Updating the navbar

### ISSUE THREAD

**Issue by Priyanshu-su30** [umeshSinghVerma/Frametagger#12]
The navbar can be updated as it seems to be mixed with the main page

**Comment by lightning-sagar** [comment]
hey i can fix the align in the navbar + will add some styling too... please assign me

**Comment by Priyanshu-su30** [comment]
I want to work on it bud

**Comment by umeshSinghVerma** [comment]
Hi @Priyanshu-su30 and @lightning-sagar! Thanks for your interest in improving the navbar. All suggestions are welcomed, but before proceeding, could you both share your design ideas or mockups on how you envision improving the navbar?

This way, we can discuss and decide the best approach. Looking forward to seeing your designs! 😊

**Comment by Priyanshu-su30** [comment]
The image here is missing and is not even in the files
![Screenshot (209)](https://github.com/user-attachments/assets/a4a68e6b-1a16-43ac-bfce-db69ac1580a4)
Please provide the image

**Comment by umeshSinghVerma** [comment]
@Priyanshu-su30 you can get essential assets from https://frametagger.com/

**Comment by Priyanshu-su30** [comment]
> Hi @Priyanshu-su30 and @lightning-sagar! Thanks for your interest in improving the navbar. All suggestions are welcomed, but before proceeding, could you both share your design ideas or mockups on how you envision improving the navbar?
> 
> This way, we can discuss and decide the best approach. Looking forward to seeing your designs! 😊

This is the navbar I created Please take a look
![Screenshot (213)](https://github.com/user-attachments/assets/5494397f-29c6-48e7-907a-de3e2c9bb104)

**Comment by umeshSinghVerma** [comment]
Hi @Priyanshu-su30, thanks for sharing the navbar design. After discussing with the team, we’ve decided that we won’t be able to adapt this design for the project.

We appreciate your efforts and hope to see more of your contributions in the future! 😊
