### ISSUE TITLE
In footer there are icon instagram,x and other as i click on then should redirect to that platform but it is not....

### ISSUE THREAD

**Issue by lightning-sagar** [umeshSinghVerma/Frametagger#13]
i cna fix it and and imporve the styling of the footer pls assign me

**Comment by umeshSinghVerma** [comment]
Hi @lightning-sagar! Thanks for your offer to fix the icons in the footer. Actually, there are no dedicated social media handles set up currently, so unfortunately we can’t create those links at this moment.

If you have any other suggestions or contributions in mind, feel free to share! 😊 Also, if you haven’t already, don’t forget to star the repository! 🌟
