### ISSUE TITLE
Adding hover efects to footer 

### ISSUE THREAD

**Issue by shobhit15082003** [umeshSinghVerma/Frametagger#17]
![Screenshot 2024-10-08 164845](https://github.com/user-attachments/assets/fc629343-c082-4aa3-a1b9-94bd9a8c25a3)

Adding hover effects to footer .

@umeshSinghVerma plz assign me this issue and also add hacktoberfest label.

**Comment by umeshSinghVerma** [comment]
Hii @shobhit15082003 Thanks for pointing that out but unfortunately our team does not take this add issue, you may consider exporing other issues.

**Comment by umeshSinghVerma** [comment]
Hii @shobhit15082003 Thanks for pointing that out but unfortunately our team does not take this add issue, You may consider exporing other issues.
