### ISSUE TITLE
PLACEMENT ROADMAP

### ISSUE THREAD

**Issue by Swastik200** [umeshSinghVerma/Frametagger#6]
USING HTML,CSS

**Comment by umeshSinghVerma** [comment]
Hi @Swastik200, I noticed you’ve opened an issue titled "PLACEMENT ROADMAP" using HTML and CSS. Could you clarify what you're trying to convey with this issue? What exactly would you like to do or contribute to the project? Looking forward to your response!

**Comment by Swastik200** [comment]
To show whole road map what to prep for placement to be shown to students

**Comment by umeshSinghVerma** [comment]
Thanks for the clarification, @Swastik200! Are you suggesting creating a visual roadmap using HTML and CSS that can help guide students in their placement preparation? If so, could you provide more details or examples of what you'd like this roadmap to include and how you envision integrating it into the project?

Looking forward to your thoughts!

**Comment by umeshSinghVerma** [comment]
Thanks for clarifying, @Swastik200! However, I won’t be incorporating this into the current project. There are already several platforms and channels dedicated to guiding students through placement preparation. I recommend checking those out for more detailed insights.

Best of luck with your efforts!

**Comment by Swastik200** [comment]
Thank you for the clarification.
